#! /usr/bin/sh
# Build the site, copy the files to the deploy repo, commits and pushes to
# remote automatically.

SITE_BUILD_DIR='public/'
SITE_DEPLOY_DIR="$HOME/work/Jesus/masher2.github.io/"

echo "Building site"
Rscript -e 'blogdown::hugo_build()' || exit 1

echo "Copying all files to the deploy repo"
cp -r $SITE_BUILD_DIR/* $SITE_DEPLOY_DIR || exit 1

echo "Deploying site"
cd $SITE_DEPLOY_DIR
git add . && git commit -m "Update" && git push && exit 0

exit 1
